import StateDepMOR.AchievabilityFinal
import StateDepMOR.PoissonSamplePathLDP
import StateDepMOR.FluidExistenceProof
import Mathlib.Probability.Distributions.Poisson.PoissonLimitThm

/-!
# Calendar/event-epoch bridge for achievability

This module relates the finite event-epoch chain to a block with an
independent random event count.  It identifies the chronological marked
prefix generated by the independent coordinate Poisson clocks with the
Poisson-count/IID-mark law through a finite-grid approximation.
-/

open MeasureTheory ProbabilityTheory

namespace StateDepMOR.PaperStatements.Network

universe u v

variable {Buffer : Type u} {Server : Type v}
variable [Fintype Buffer] [Fintype Server]
variable [DecidableEq Buffer] [DecidableEq Server]
variable [Nonempty Buffer] [Nonempty Server]

variable (N : StateDepMOR.Network Buffer Server)

private theorem poissonMeasure_zero_eq_dirac :
    ProbabilityTheory.poissonMeasure 0 = Measure.dirac 0 := by
  apply Measure.ext_of_singleton
  intro n
  rw [ProbabilityTheory.poissonMeasure_singleton]
  by_cases hn : n = 0
  · subst n
    simp
  · simp [hn]

private theorem finsetSum_hasLaw_poisson
    {Omega I : Type*} [MeasurableSpace Omega]
    [DecidableEq I]
    (mu : Measure Omega) [IsProbabilityMeasure mu]
    (X : I -> Omega -> Nat) (q : I -> NNReal)
    (hindep : iIndepFun X mu)
    (hmeas : forall i, Measurable (X i))
    (hlaw : forall i, HasLaw (X i)
      (ProbabilityTheory.poissonMeasure (q i)) mu)
    (s : Finset I) :
    HasLaw
      (Finset.sum s X)
      (ProbabilityTheory.poissonMeasure (Finset.sum s q)) mu := by
  induction s using Finset.induction_on with
  | empty =>
      have hdirac :
          HasLaw (fun _ : Omega => (0 : Nat)) (Measure.dirac 0) mu :=
        hasLaw_dirac_of_ae_eq (Filter.Eventually.of_forall fun _ => rfl)
      rw [show Finset.sum (∅ : Finset I) X =
          (fun _ : Omega => (0 : Nat)) by
        funext omega
        simp]
      simpa [poissonMeasure_zero_eq_dirac] using hdirac
  | @insert a s ha ih =>
      have hi :=
        hindep.indepFun_finsetSum_of_notMem hmeas ha
      have hadd :=
        hi.hasLaw_add_poissonMeasure ih (hlaw a)
      simpa [Finset.sum_insert ha, add_comm] using hadd

private theorem tokenVectorLaw_succ_eq_bind (n : Nat) :
    N.tokenVectorLaw (n + 1) =
      N.tokenLaw.bind fun jk =>
        (N.tokenVectorLaw n).map (Fin.cons jk) := by
  classical
  apply PMF.ext
  intro tokens
  apply (ENNReal.toReal_eq_toReal_iff'
    ((N.tokenVectorLaw (n + 1)).apply_ne_top tokens)
    ((N.tokenLaw.bind fun jk =>
      (N.tokenVectorLaw n).map (Fin.cons jk)).apply_ne_top tokens)).mp
  rw [N.tokenVectorLaw_apply_toReal]
  rw [PMF.bind_apply, tsum_fintype]
  rw [ENNReal.toReal_sum (fun jk _ =>
    ENNReal.mul_ne_top (N.tokenLaw.apply_ne_top jk)
      (((N.tokenVectorLaw n).map (Fin.cons jk)).apply_ne_top tokens))]
  simp_rw [ENNReal.toReal_mul]
  simp_rw [PMF.map_apply, tsum_fintype]
  rw [Fin.prod_univ_succ]
  rw [Finset.sum_eq_single (tokens 0)]
  next =>
    rw [Finset.sum_eq_single (fun i => tokens i.succ)]
    next =>
      have hself :
          tokens = Fin.cons (tokens 0) (fun i => tokens i.succ) :=
        (Fin.cons_self_tail tokens).symm
      rw [if_pos hself, N.tokenVectorLaw_apply_toReal]
    next =>
      intro tail _htail hne
      have hnot :
          Not (tokens = Fin.cons (tokens 0) tail) := by
        intro h
        apply hne
        funext i
        exact (congrFun h i.succ).symm
      simp [hnot]
    next =>
      simp
  next =>
    intro jk _hjk hne
    have hcons (tail : Fin n -> Server × Buffer) :
        Not (tokens = Fin.cons jk tail) := by
      intro h
      apply hne
      exact (congrFun h 0).symm
    simp [hcons]
  next =>
    simp

private theorem nStepLaw_pure_succ_first
    {K : Nat} (U : N.DeterministicStationaryPolicy K)
    (x : JobState Buffer K) (n : Nat) :
    N.nStepLaw U (PMF.pure x) (n + 1) =
      (N.transitionPMF U x).bind
        (fun y => N.nStepLaw U (PMF.pure y) n) := by
  induction n generalizing x with
  | zero =>
      simpa using (PMF.bind_pure (N.transitionPMF U x)).symm
  | succ n ih =>
      rw [N.nStepLaw_succ, ih, PMF.bind_bind]
      apply congrArg
      funext y
      exact N.nStepLaw_succ U (PMF.pure y) n

private theorem nStepLaw_pure_eq_tokenVectorLaw_map_runTokens
    {K : Nat} (U : N.DeterministicStationaryPolicy K)
    (x : JobState Buffer K) (n : Nat) :
    N.nStepLaw U (PMF.pure x) n =
      (N.tokenVectorLaw n).map
        (fun tokens => N.runTokens U x (List.ofFn tokens)) := by
  induction n generalizing x with
  | zero =>
      rw [N.nStepLaw_zero]
      have hrun :
          (fun tokens : Fin 0 -> Server × Buffer =>
            N.runTokens U x (List.ofFn tokens)) =
            Function.const
              (Fin 0 -> Server × Buffer) x := by
        funext tokens
        simp [StateDepMOR.Network.runTokens]
      rw [hrun, PMF.map_const]
  | succ n ih =>
      rw [nStepLaw_pure_succ_first N U x n]
      rw [tokenVectorLaw_succ_eq_bind N n, PMF.map_bind]
      rw [StateDepMOR.Network.transitionPMF, PMF.bind_map]
      apply congrArg
      funext jk
      calc
        (Function.comp (fun y => N.nStepLaw U (PMF.pure y) n)
            (N.queueStep U x)) jk =
            N.nStepLaw U (PMF.pure (N.queueStep U x jk)) n := rfl
        _ = (N.tokenVectorLaw n).map
            (fun tokens =>
              N.runTokens U (N.queueStep U x jk)
                (List.ofFn tokens)) :=
          ih (N.queueStep U x jk)
        _ = (N.tokenVectorLaw n).map
            (Function.comp
              (fun tokens => N.runTokens U x (List.ofFn tokens))
              (Fin.cons jk)) := by
          apply congrArg (fun f :
            (Fin n -> Server × Buffer) ->
                JobState Buffer K =>
              (N.tokenVectorLaw n).map f)
          funext tokens
          simp [Function.comp_def, List.ofFn_succ,
            StateDepMOR.Network.runTokens]
        _ = ((N.tokenVectorLaw n).map (Fin.cons jk)).map
            (fun tokens => N.runTokens U x (List.ofFn tokens)) := by
          exact (PMF.map_comp
            (p := N.tokenVectorLaw n) (f := Fin.cons jk)
            (g := fun tokens : Fin (n + 1) ->
              Server × Buffer =>
                N.runTokens U x (List.ofFn tokens))).symm

/-- Endpoint law obtained by first drawing an event count and then drawing
that many IID marked tokens with law `N.tokenLaw`. -/
noncomputable def poissonizedTokenEndpointLaw
    {K : Nat} (U : N.DeterministicStationaryPolicy K)
    (countLaw : PMF Nat) (x : JobState Buffer K) :
    PMF (JobState Buffer K) :=
  countLaw.bind fun n =>
    (N.tokenVectorLaw n).map fun tokens =>
      N.runTokens U x (List.ofFn tokens)

/-- The explicit Poisson-count/IID-mark construction is exactly the
randomized event-epoch kernel. -/
theorem poissonizedTokenEndpointLaw_eq_randomizedEventEpochKernel
    {K : Nat} (U : N.DeterministicStationaryPolicy K)
    (countLaw : PMF Nat) (x : JobState Buffer K) :
    poissonizedTokenEndpointLaw N U countLaw x =
      randomizedEventEpochKernel N U countLaw x := by
  unfold poissonizedTokenEndpointLaw randomizedEventEpochKernel
  apply congrArg
  funext n
  exact (nStepLaw_pure_eq_tokenVectorLaw_map_runTokens N U x n).symm

/-- Mixing the explicit Poisson-count/IID-mark endpoint law against an
invariant event-epoch PMF leaves that PMF unchanged. -/
theorem bind_poissonizedTokenEndpointLaw_eq_of_isInvariant
    {K : Nat} (U : N.DeterministicStationaryPolicy K)
    (pi : PMF (JobState Buffer K)) (countLaw : PMF Nat)
    (hinvariant : N.IsInvariantPMF U pi) :
    pi.bind (poissonizedTokenEndpointLaw N U countLaw) = pi := by
  rw [show poissonizedTokenEndpointLaw N U countLaw =
      randomizedEventEpochKernel N U countLaw by
    funext x
    exact poissonizedTokenEndpointLaw_eq_randomizedEventEpochKernel
      N U countLaw x]
  exact bind_randomizedEventEpochKernel_eq_of_isInvariant
    N U pi countLaw hinvariant

/-- Queue endpoint of the original chronological calendar construction. -/
noncomputable def calendarBlockEndpoint
    (K : PNat) (U : N.DeterministicStationaryPolicy (K : Nat))
    (x : JobState Buffer (K : Nat))
    (omega : StateDepMOR.Network.CalendarPoissonSample
      (Buffer := Buffer) (Server := Server)) (H : Real) :
    JobState Buffer (K : Nat) :=
  N.runTokens U x
    (N.calendarTokenPrefix K omega H)

/-- The calendar scaled queue state is the normalized coordinate vector of
the same chronological finite-queue endpoint. -/
theorem calendarScaledQueueStateFrom_eq_calendarBlockEndpoint
    (U : N.DeterministicPolicySequence) (K : PNat)
    (x : JobState Buffer (K : Nat))
    (omega : StateDepMOR.Network.CalendarPoissonSample
      (Buffer := Buffer) (Server := Server)) (H : Real) (i : Buffer) :
    N.calendarScaledQueueStateFrom U K x omega H i =
      ((N.runTokens (U K) x
        (N.calendarTokenPrefix K omega H) i : Nat) : Real) /
        ((K : Nat) : Real) := by
  rfl

/-- Calendar endpoints agree whenever their chronological marked prefixes
agree.  This is the deterministic half of the stochastic bridge. -/
theorem calendarBlockEndpoint_eq_of_tokenPrefix_eq
    (K : PNat) (U : N.DeterministicStationaryPolicy (K : Nat))
    (x : JobState Buffer (K : Nat))
    {tokens : List (Server × Buffer)}
    {omega : StateDepMOR.Network.CalendarPoissonSample
      (Buffer := Buffer) (Server := Server)} {H : Real}
    (hprefix : N.calendarTokenPrefix K omega H = tokens) :
    calendarBlockEndpoint N K U x omega H =
      N.runTokens U x tokens := by
  simp only [calendarBlockEndpoint]
  rw [hprefix]

/-- Total number of marked arrivals in a calendar block. -/
noncomputable def calendarBlockEventCount
    (K : PNat)
    (omega : StateDepMOR.Network.CalendarPoissonSample
      (Buffer := Buffer) (Server := Server))
    (H : Real) : Nat :=
  Finset.sum Finset.univ fun j : Server =>
    Finset.sum Finset.univ fun k : Buffer =>
      N.calendarTokenCount K omega H j k

/-- Poisson parameter for the total number of calendar events by time `H`.
The `max` matches the concrete calendar construction at nonpositive times. -/
noncomputable def calendarBlockCountParameter
    (K : PNat) (H : Real) : NNReal :=
  ⟨((K : Nat) : Real) * max H 0,
    mul_nonneg (by positivity) (le_max_right H 0)⟩

/-- Explicit count law used to Poissonize the event-epoch chain. -/
noncomputable def calendarBlockCountLaw
    (K : PNat) (H : Real) : PMF Nat :=
  (ProbabilityTheory.poissonMeasure
    (calendarBlockCountParameter K H)).toPMF

private noncomputable def calendarBlockCoordinateParameter
    (K : PNat) (H : Real)
    (p : Sigma fun _ : Server => Buffer) : NNReal :=
  ⟨N.coordinateOperationalTime K H p.1 p.2,
    mul_nonneg
      (mul_nonneg (by positivity) (N.phi_nonneg p.1 p.2))
      (le_max_right H 0)⟩

private theorem sum_calendarBlockCoordinateParameter
    (K : PNat) (H : Real) :
    Finset.univ.sum (calendarBlockCoordinateParameter N K H) =
      calendarBlockCountParameter K H := by
  apply NNReal.eq
  simp only [NNReal.coe_sum, calendarBlockCoordinateParameter,
    calendarBlockCountParameter]
  rw [Fintype.sum_sigma]
  simp only [StateDepMOR.Network.coordinateOperationalTime]
  calc
    (Finset.univ.sum fun j : Server =>
      Finset.univ.sum fun k : Buffer =>
        ((K : Nat) : Real) * N.phi j k * max H 0) =
        Finset.univ.sum (fun j : Server =>
          (((K : Nat) : Real) *
            Finset.univ.sum (fun k : Buffer => N.phi j k)) *
              max H 0) := by
      apply Finset.sum_congr rfl
      intro j _hj
      rw [Finset.mul_sum, Finset.sum_mul]
    _ =
        (((K : Nat) : Real) *
          (Finset.univ.sum fun j : Server =>
            Finset.univ.sum fun k : Buffer => N.phi j k)) *
          max H 0 := by
      rw [Finset.mul_sum, Finset.sum_mul]
    _ = ((K : Nat) : Real) * max H 0 := by
      rw [N.total_rate]
      ring

/-- The total number of arrivals in the concrete calendar block has the
Poisson law with parameter `K * max H 0`. -/
theorem calendarBlockEventCount_hasLaw
    (K : PNat) (H : Real) :
    HasLaw
      (fun omega : StateDepMOR.Network.CalendarPoissonSample
          (Buffer := Buffer) (Server := Server) =>
        calendarBlockEventCount N K omega H)
      (ProbabilityTheory.poissonMeasure
        (calendarBlockCountParameter K H))
      N.calendarPoissonMeasure := by
  let X :
      (Sigma fun _ : Server => Buffer) ->
        StateDepMOR.Network.CalendarPoissonSample
          (Buffer := Buffer) (Server := Server) -> Nat :=
    fun p omega => N.calendarTokenCount K omega H p.1 p.2
  let q : (Sigma fun _ : Server => Buffer) -> NNReal :=
    calendarBlockCoordinateParameter N K H
  have hindep : iIndepFun X N.calendarPoissonMeasure := by
    simpa [X] using
      StateDepMOR.PoissonSamplePath.calendarTokenCount_coordinate_iIndep
        N K (fun _ => H)
  have hmeas : forall p, Measurable (X p) := by
    intro p
    exact StateDepMOR.PoissonSamplePath.measurable_calendarTokenCount
      N K H p.1 p.2
  have hlaw : forall p, HasLaw (X p)
      (ProbabilityTheory.poissonMeasure (q p))
      N.calendarPoissonMeasure := by
    intro p
    simpa [X, q, calendarBlockCoordinateParameter] using
      StateDepMOR.Network.calendarTokenCount_hasLaw_poisson
        N K H p.1 p.2
  have hsum := finsetSum_hasLaw_poisson
    N.calendarPoissonMeasure X q hindep hmeas hlaw Finset.univ
  rw [sum_calendarBlockCoordinateParameter N K H] at hsum
  convert hsum using 1
  funext omega
  unfold calendarBlockEventCount
  rw [Finset.sum_apply, Fintype.sum_sigma]

/-- Measure form of `calendarBlockEventCount_hasLaw`, using the exact PMF
passed to `randomizedEventEpochKernel`. -/
theorem calendarBlockEventCount_hasLaw_countLaw
    (K : PNat) (H : Real) :
    HasLaw
      (fun omega : StateDepMOR.Network.CalendarPoissonSample
          (Buffer := Buffer) (Server := Server) =>
        calendarBlockEventCount N K omega H)
      (calendarBlockCountLaw K H).toMeasure
      N.calendarPoissonMeasure := by
  rw [calendarBlockCountLaw, Measure.toPMF_toMeasure]
  exact calendarBlockEventCount_hasLaw N K H

/-- The chronological merge contains exactly all coordinate arrivals and
therefore has length equal to the total coordinate count. -/
theorem calendarTokenPrefix_length
    (K : PNat)
    (omega : StateDepMOR.Network.CalendarPoissonSample
      (Buffer := Buffer) (Server := Server))
    (H : Real) :
    (N.calendarTokenPrefix K omega H).length =
      calendarBlockEventCount N K omega H := by
  classical
  unfold StateDepMOR.Network.calendarTokenPrefix
    StateDepMOR.Network.chronologicalCalendarEvents
    StateDepMOR.Network.rawCalendarEvents calendarBlockEventCount
  simp only [List.length_map, List.length_insertionSort,
    List.length_flatMap, List.length_map,
    Finset.length_toList, Finset.card_range]
  have hsumBuffer (f : Buffer -> Nat) :
      (Finset.univ.toList.map f).sum = Finset.sum Finset.univ f := by
    have h := congrArg (fun s : Multiset Buffer =>
      (Multiset.map f s).sum)
      (Finset.coe_toList (Finset.univ : Finset Buffer))
    calc
      (Finset.univ.toList.map f).sum =
          (Multiset.map f
            (↑((Finset.univ : Finset Buffer).toList))).sum := by
        rw [<- Multiset.sum_coe]
        rfl
      _ = (Multiset.map f
          (Finset.univ : Finset Buffer).val).sum := h
      _ = Finset.sum Finset.univ f := rfl
  have hsumServer (f : Server -> Nat) :
      (Finset.univ.toList.map f).sum = Finset.sum Finset.univ f := by
    have h := congrArg (fun s : Multiset Server =>
      (Multiset.map f s).sum)
      (Finset.coe_toList (Finset.univ : Finset Server))
    calc
      (Finset.univ.toList.map f).sum =
          (Multiset.map f
            (↑((Finset.univ : Finset Server).toList))).sum := by
        rw [<- Multiset.sum_coe]
        rfl
      _ = (Multiset.map f
          (Finset.univ : Finset Server).val).sum := h
      _ = Finset.sum Finset.univ f := rfl
  rw [hsumServer]
  apply Finset.sum_congr rfl
  intro j _hj
  exact hsumBuffer fun k => N.calendarTokenCount K omega H j k

/-- At a positive system size, the natural-index adapter used by
`calendarPathLaw` returns that same system size. -/
theorem positiveSize_pnat_val (K : PNat) :
    StateDepMOR.PoissonSamplePath.positiveSize (K : Nat) = K := by
  apply Subtype.ext
  simp only [StateDepMOR.PoissonSamplePath.positiveSize]
  exact max_eq_left (Nat.one_le_iff_ne_zero.mpr K.ne_zero)

/-- Pointwise calendar/J1 bridge for a fixed finite initial state.

If every calendar sample whose chronological queue endpoint satisfies
`Target` has its scaled primitive path in the measurable J1 event `F`, then
the endpoint-event mass is at most the calendar path-law mass of `F`. -/
theorem calendarBlockEndpointEvent_le_calendarPathLaw
    {H : Real} (hH : 0 < H)
    (K : PNat) (U : N.DeterministicStationaryPolicy (K : Nat))
    (x : JobState Buffer (K : Nat))
    (Target : JobState Buffer (K : Nat) -> Prop)
    (F : Set (StateDepMOR.PoissonSamplePath.Path
      (Buffer := Buffer) (Server := Server) H))
    (hF : MeasurableSet F)
    (hcontain :
      forall omega :
          StateDepMOR.Network.CalendarPoissonSample
            (Buffer := Buffer) (Server := Server),
        Target (calendarBlockEndpoint N K U x omega H) ->
          StateDepMOR.PoissonSamplePath.calendarPath N H K omega ∈ F) :
    N.calendarPoissonMeasure
        {omega | Target (calendarBlockEndpoint N K U x omega H)} <=
      StateDepMOR.PoissonSamplePath.calendarPathLaw
        N H (K : Nat) F := by
  rw [StateDepMOR.PoissonSamplePath.calendarPathLaw_apply
    N hH (K : Nat) hF]
  apply measure_mono
  intro omega homega
  change
    StateDepMOR.PoissonSamplePath.calendarPath N H
      (StateDepMOR.PoissonSamplePath.positiveSize (K : Nat)) omega ∈ F
  rw [positiveSize_pnat_val K]
  exact hcontain omega homega

/-- Real-valued form of
`calendarBlockEndpointEvent_le_calendarPathLaw`, ready for the pointwise
`ENNReal.ofReal` premise consumed by `AchievabilityRateTransfer`. -/
theorem ofReal_calendarBlockEndpointEvent_le_calendarPathLaw
    {H : Real} (hH : 0 < H)
    (K : PNat) (U : N.DeterministicStationaryPolicy (K : Nat))
    (x : JobState Buffer (K : Nat))
    (Target : JobState Buffer (K : Nat) -> Prop)
    (F : Set (StateDepMOR.PoissonSamplePath.Path
      (Buffer := Buffer) (Server := Server) H))
    (hF : MeasurableSet F)
    (hcontain :
      forall omega :
          StateDepMOR.Network.CalendarPoissonSample
            (Buffer := Buffer) (Server := Server),
        Target (calendarBlockEndpoint N K U x omega H) ->
          StateDepMOR.PoissonSamplePath.calendarPath N H K omega ∈ F) :
    ENNReal.ofReal
        (N.calendarPoissonMeasure.real
          {omega | Target (calendarBlockEndpoint N K U x omega H)}) <=
      StateDepMOR.PoissonSamplePath.calendarPathLaw
        N H (K : Nat) F := by
  rw [measureReal_def]
  rw [ENNReal.ofReal_toReal (measure_ne_top N.calendarPoissonMeasure _)]
  exact calendarBlockEndpointEvent_le_calendarPathLaw
    N hH K U x Target F hF hcontain

/-- Family-level pointwise bound in exactly the form consumed by
`AchievabilityRateTransfer`.

The event `F` is fixed across system sizes.  All finite-state information is
kept in the concrete chronological endpoint event. -/
theorem lossFamily_le_calendarPathLaw_of_calendarEndpoint
    {H : Real} (hH : 0 < H)
    (U : N.DeterministicPolicySequence)
    (initial : forall K : PNat, JobState Buffer (K : Nat))
    (Target : forall K : PNat, JobState Buffer (K : Nat) -> Prop)
    (loss : PNat -> Real)
    (F : Set (StateDepMOR.PoissonSamplePath.Path
      (Buffer := Buffer) (Server := Server) H))
    (hF : MeasurableSet F)
    (hloss :
      forall K : PNat,
        loss K <=
          N.calendarPoissonMeasure.real
            {omega |
              Target K
                (calendarBlockEndpoint
                  N K (U K) (initial K) omega H)})
    (hcontain :
      forall (K : PNat)
        (omega : StateDepMOR.Network.CalendarPoissonSample
          (Buffer := Buffer) (Server := Server)),
        Target K
            (calendarBlockEndpoint N K (U K) (initial K) omega H) ->
          StateDepMOR.PoissonSamplePath.calendarPath N H K omega ∈ F) :
    forall K : PNat,
      ENNReal.ofReal (loss K) <=
        StateDepMOR.PoissonSamplePath.calendarPathLaw
          N H (K : Nat) F := by
  intro K
  exact (ENNReal.ofReal_le_ofReal (hloss K)).trans
    (ofReal_calendarBlockEndpointEvent_le_calendarPathLaw
      N hH K (U K) (initial K) (Target K) F hF (hcontain K))

#check poissonizedTokenEndpointLaw_eq_randomizedEventEpochKernel
#check bind_poissonizedTokenEndpointLaw_eq_of_isInvariant
#check calendarScaledQueueStateFrom_eq_calendarBlockEndpoint
#check calendarBlockEndpoint_eq_of_tokenPrefix_eq
#check calendarTokenPrefix_length
#check calendarBlockEndpointEvent_le_calendarPathLaw
#check ofReal_calendarBlockEndpointEvent_le_calendarPathLaw
#check lossFamily_le_calendarPathLaw_of_calendarEndpoint

#print axioms poissonizedTokenEndpointLaw_eq_randomizedEventEpochKernel
#print axioms bind_poissonizedTokenEndpointLaw_eq_of_isInvariant
#print axioms ofReal_calendarBlockEndpointEvent_le_calendarPathLaw
#print axioms lossFamily_le_calendarPathLaw_of_calendarEndpoint

end StateDepMOR.PaperStatements.Network

