import StateDepMOR.FluidConsistency
import StateDepMOR.TokenIID
import StateDepMOR.FiniteQueueTrajectories
import Mathlib.Analysis.SpecificLimits.Basic

/-!
# Concrete event-epoch stochastic execution

This module runs the finite queue on prefixes of the canonical IID marked
token path. At fluid time `t`, the execution has processed
`floor(K * max(t, 0))` tokens. The state and allocation paths use the same
prefix and the same queue recursion.

The final theorem proves the nominal subsequential-input clause on the common
almost-sure event supplied by the strong law in `TokenIID.lean`.
-/

open Filter MeasureTheory Set

namespace StateDepMOR

universe u v

variable {Buffer : Type u} {Server : Type v}
variable [Fintype Buffer] [Fintype Server]
variable [DecidableEq Buffer] [DecidableEq Server]
variable [Nonempty Buffer]

namespace Network

attribute [local instance] tokenTypeMeasurableSpace

variable (N : Network Buffer Server)

/-- Number of event epochs processed by fluid time `t`. -/
noncomputable def eventEpochCount
    (_N : Network Buffer Server) (K : PNat) (t : Real) : Nat :=
  Nat.floor (max t 0 * ((K : Nat) : Real))

/-- The first `n` marked tokens on a canonical token path. -/
def eventTokenPrefix (n : Nat) (omega : N.TokenPath) :
    List (TokenType (Buffer := Buffer) (Server := Server)) :=
  List.ofFn (fun r : Fin n => N.tokenAt r omega)

/-- A fixed concrete initial state at each positive system size. -/
noncomputable def eventInitialState
    (_N : Network Buffer Server) (K : PNat) :
    JobState Buffer (K : Nat) :=
  Classical.choice
    (inferInstance : Nonempty (JobState Buffer (K : Nat)))

/-- Cumulative allocations generated while processing a token list.

The coordinate `(i,j,k)` counts tokens of type `(j,k)` assigned to source
buffer `i`. The recursive state is exactly the state used by `queueStep`.
-/
def runAllocationCount {K : Nat}
    (U : N.DeterministicStationaryPolicy K) :
    JobState Buffer K ->
      List (TokenType (Buffer := Buffer) (Server := Server)) ->
      Buffer -> Server -> Buffer -> Nat
  | _, [], _, _, _ => 0
  | x, jk :: rest, i, j, k =>
      (if U x jk.1 jk.2 = some i /\ jk.1 = j /\ jk.2 = k then 1 else 0) +
        runAllocationCount U (N.queueStep U x jk) rest i j k

/-- Fluid-scaled cumulative input for one marked-token coordinate. -/
noncomputable def scaledTokenInput
    (K : PNat) (omega : N.TokenPath) (t : Real)
    (j : Server) (k : Buffer) : Real :=
  let n := N.eventEpochCount K t
  ((n : Real) / ((K : Nat) : Real)) *
    N.empiricalFrequency (j, k) n omega

/-- Fluid-scaled queue state generated by the concrete token prefix. -/
noncomputable def scaledQueueState
    (U : N.DeterministicPolicySequence)
    (K : PNat) (omega : N.TokenPath) (t : Real) (i : Buffer) : Real :=
  let tokens := N.eventTokenPrefix (N.eventEpochCount K t) omega
  ((N.runTokens (U K) (N.eventInitialState K) tokens i : Nat) : Real) /
    ((K : Nat) : Real)

/-- Fluid-scaled cumulative allocation generated by the concrete prefix. -/
noncomputable def scaledAllocation
    (U : N.DeterministicPolicySequence)
    (K : PNat) (omega : N.TokenPath) (t : Real)
    (i : Buffer) (j : Server) (k : Buffer) : Real :=
  let tokens := N.eventTokenPrefix (N.eventEpochCount K t) omega
  (N.runAllocationCount (U K) (N.eventInitialState K) tokens i j k : Real) /
    ((K : Nat) : Real)

/-- The concrete scaled execution driven by the canonical IID token path. -/
noncomputable def eventEpochExecution :
    N.ScaledStochasticExecution N.TokenPath where
  probability :=
    (show ProbabilityMeasure N.TokenPath from
      ⟨N.tokenPathMeasure, inferInstance⟩)
  input := fun K omega t j k => N.scaledTokenInput K omega t j k
  state := fun U K omega t i => N.scaledQueueState U K omega t i
  allocation := fun U K omega t i j k =>
    N.scaledAllocation U K omega t i j k

private theorem pnatVal_strictMono
    {K : Nat -> PNat} (hK : StrictMono K) :
    StrictMono (fun r => (K r : Nat)) := by
  intro r s hrs
  exact hK hrs

private theorem uniformlyOnIcc_tendsto_at
    {Index : Type*} {T : Real}
    {f : Nat -> Real -> Index -> Real}
    {g : Real -> Index -> Real}
    (h : UniformlyOnIcc T f g)
    {t : Real} (ht : t ∈ Icc (0 : Real) T) (i : Index) :
    Tendsto (fun r => f r t i) atTop (nhds (g t i)) := by
  rw [Metric.tendsto_atTop]
  intro epsilon hepsilon
  obtain ⟨r0, hr0⟩ := h epsilon hepsilon
  refine ⟨r0, fun r hr => ?_⟩
  simpa only [Real.dist_eq] using hr0 r hr t ht i

/-- On the simultaneous strong-law event, every fixed-time input coordinate
converges along every strictly increasing system-size subsequence. -/
theorem scaledTokenInput_tendsto
    (omega : N.TokenPath)
    (homega :
      forall jk : TokenType (Buffer := Buffer) (Server := Server),
        Tendsto (fun n => N.empiricalFrequency jk n omega)
          atTop (nhds (N.phi jk.1 jk.2)))
    (K : Nat -> PNat) (hK : StrictMono K)
    (t : Real) (ht : 0 <= t) (j : Server) (k : Buffer) :
    Tendsto
      (fun r => N.scaledTokenInput (K r) omega t j k)
      atTop (nhds (N.phi j k * t)) := by
  rcases ht.eq_or_lt with rfl | ht
  · simp [scaledTokenInput, eventEpochCount]
  · have hKval :
        Tendsto (fun r => (K r : Nat)) atTop atTop :=
      (pnatVal_strictMono hK).tendsto_atTop
    have hcount :
        Tendsto (fun r => N.eventEpochCount (K r) t) atTop atTop := by
      have hfloor :=
        (tendsto_nat_floor_mul_atTop t ht).comp hKval
      simp only [eventEpochCount, max_eq_left ht.le]
      convert hfloor using 1
      funext r
      rfl
    have hfrequency :
        Tendsto
          (fun r =>
            N.empiricalFrequency (j, k)
              (N.eventEpochCount (K r) t) omega)
          atTop (nhds (N.phi j k)) :=
      (homega (j, k)).comp hcount
    have hKreal :
        Tendsto (fun r => (((K r : Nat) : Real))) atTop atTop :=
      tendsto_natCast_atTop_atTop.comp hKval
    have hratio :
        Tendsto
          (fun r =>
            ((N.eventEpochCount (K r) t : Nat) : Real) /
              ((K r : Nat) : Real))
          atTop (nhds t) := by
      have hfloorRatio :=
        (tendsto_nat_floor_mul_div_atTop (R := Real) ht.le).comp hKreal
      simp only [eventEpochCount, max_eq_left ht.le]
      convert hfloorRatio using 1
      funext r
      rfl
    simpa [scaledTokenInput, mul_comm] using hratio.mul hfrequency

/-- Concrete proof of the almost-sure nominal subsequential-input clause in
`lem:fms-existence` for the event-epoch execution. -/
theorem eventEpochExecution_subsequentialInput :
    N.PoissonSubsequentialInputReadback N.eventEpochExecution := by
  intro T hT U K hK A X
  filter_upwards [N.all_empiricalFrequencies_tendsto_phi_ae] with omega homega
  intro hconverges
  intro t ht j k
  have hcandidate :
      Tendsto
        (fun r =>
          N.scaledTokenInput (K r) omega t j k)
        atTop (nhds (A omega t j k)) := by
    exact uniformlyOnIcc_tendsto_at hconverges.1 ht (j, k)
  have hnominal :
      Tendsto
        (fun r =>
          N.scaledTokenInput (K r) omega t j k)
        atTop (nhds (N.phi j k * t)) :=
    N.scaledTokenInput_tendsto omega homega K hK t ht.1 j k
  exact tendsto_nhds_unique hcandidate hnominal

end Network

end StateDepMOR
