import StateDepMOR.RecurrentClassPerformance
import StateDepMOR.HallCriticalEquality
import StateDepMOR.AchievabilityCalendarLaw
import StateDepMOR.MainAssembly

/-!
# Bridge to the paper's calendar-time performance measure

The paper measures cumulative wasted service opportunities in continuous
calendar time, starts the finite queue in a recurrent-class invariant law,
and then minimizes over recurrent classes.  This module identifies that
quantity with the event-epoch loss used by the existing main theorem.
-/

open Filter MeasureTheory ProbabilityTheory Set
open scoped BigOperators ENNReal NNReal Topology

noncomputable section

namespace StateDepMOR

namespace PMF

universe w z

/-- The nonnegative expectation of `f` under a PMF, represented in
`ENNReal` so that no integrability side condition is hidden. -/
noncomputable def lExpectation {A : Type w}
    (p : PMF A) (f : A -> ENNReal) : ENNReal :=
  ∑' a, p a * f a

theorem lExpectation_pure {A : Type w}
    (a : A) (f : A -> ENNReal) :
    lExpectation (PMF.pure a) f = f a := by
  simp [lExpectation, PMF.pure_apply]

theorem lExpectation_bind {A : Type w} {B : Type z}
    (p : PMF A) (q : A -> PMF B) (f : B -> ENNReal) :
    lExpectation (p.bind q) f =
      ∑' a, p a * lExpectation (q a) f := by
  unfold lExpectation
  simp only [PMF.bind_apply]
  simpa only [ENNReal.tsum_mul_left.symm,
    ENNReal.tsum_mul_right.symm, mul_assoc, mul_left_comm, mul_comm] using
    (ENNReal.tsum_comm :
      (∑' b, ∑' a, p a * q a b * f b) =
        ∑' a, ∑' b, p a * q a b * f b)

theorem lExpectation_map {A : Type w} {B : Type z}
    (p : PMF A) (g : A -> B) (f : B -> ENNReal) :
    lExpectation (p.map g) f =
      lExpectation p (fun a => f (g a)) := by
  rw [← PMF.bind_pure_comp]
  rw [lExpectation_bind]
  change
    (∑' a, p a * lExpectation ((PMF.pure ∘ g) a) f) =
      ∑' a, p a * f (g a)
  apply tsum_congr
  intro a
  rw [Function.comp_apply, lExpectation_pure]

end PMF

/-- The first moment of a Poisson law. -/
theorem ProbabilityTheory.hasSum_poissonMeasure_mul_nat
    (r : NNReal) :
    HasSum
      (fun n : Nat =>
        (Real.exp (-(r : Real)) * (r : Real) ^ n / n.factorial) *
          (n : Real))
      (r : Real) := by
  let f : Nat -> Real := fun n =>
    (Real.exp (-(r : Real)) * (r : Real) ^ n / n.factorial) *
      (n : Real)
  have hbase :=
    (ProbabilityTheory.hasSum_one_poissonMeasure r).mul_left (r : Real)
  have hshift : HasSum (fun n => f (n + 1)) (r : Real) := by
    simpa only [mul_one] using HasSum.congr_fun hbase (fun n => by
      dsimp only [f]
      rw [Nat.factorial_succ, Nat.cast_mul, Nat.cast_add, Nat.cast_one,
        pow_succ]
      field_simp)
  apply (hasSum_nat_add_iff' 1).mp
  simpa [f] using hshift

universe u v

variable {Buffer : Type u} {Server : Type v}
variable [Fintype Buffer] [Fintype Server]
variable [DecidableEq Buffer] [DecidableEq Server]
variable [Nonempty Buffer] [Nonempty Server]

namespace Network

variable (N : Network Buffer Server)

/-- Cumulative wasted service opportunities along the original
chronological calendar-time construction. -/
noncomputable def calendarCumulativeWaste
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (x : JobState Buffer (K : Nat))
    (omega : StateDepMOR.Network.CalendarPoissonSample
      (Buffer := Buffer) (Server := Server)) (H : Real) : Real :=
  N.trajectoryWaste U x (N.calendarTokenPrefix K omega H)

/-- The PMF of cumulative calendar waste from one fixed initial queue
state. -/
noncomputable def calendarWasteLawFrom
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (x : JobState Buffer (K : Nat)) (H : Real) : PMF Real :=
  (StateDepMOR.Achievability.CalendarLaw.calendarTokenListLaw N K H).map
    (N.trajectoryWaste U x)

/-- The cumulative-waste variable generated by the concrete independent
Poisson clocks has the explicit Poisson-count/IID-token waste law. -/
theorem calendarCumulativeWaste_hasLaw
    (K : PNat) {H : Real} (hH : 0 < H)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (x : JobState Buffer (K : Nat)) :
    HasLaw
      (fun omega : StateDepMOR.Network.CalendarPoissonSample
          (Buffer := Buffer) (Server := Server) =>
        N.calendarCumulativeWaste K U x omega H)
      (N.calendarWasteLawFrom K U x H).toMeasure
      N.calendarPoissonMeasure := by
  letI : MeasurableSpace
      (List (Server × Buffer)) := Top.top
  have hprefix :=
    StateDepMOR.Achievability.CalendarLaw.calendarTokenPrefix_hasLaw
      N K hH
  have hwasteMeasurable :
      Measurable (N.trajectoryWaste U x) :=
    Measurable.of_discrete
  have hwasteLaw :
      HasLaw
        (N.trajectoryWaste U x)
        (N.calendarWasteLawFrom K U x H).toMeasure
        (StateDepMOR.Achievability.CalendarLaw.calendarTokenListLaw
          N K H).toMeasure := by
    refine ⟨hwasteMeasurable.aemeasurable, ?_⟩
    exact PMF.toMeasure_map
      (N.trajectoryWaste U x)
      (StateDepMOR.Achievability.CalendarLaw.calendarTokenListLaw N K H)
      hwasteMeasurable
  simpa [calendarCumulativeWaste, Function.comp_def] using
    hwasteLaw.comp hprefix

/-- Calendar waste law after independently drawing the initial queue state
from `pi`. -/
noncomputable def calendarWasteLaw
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat))) (H : Real) : PMF Real :=
  pi.bind fun x => N.calendarWasteLawFrom K U x H

/-- The nonnegative expected cumulative calendar waste.  This is the
expectation of the concrete calendar waste law, not an event-epoch alias. -/
noncomputable def calendarExpectedWasteENN
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat))) (H : Real) : ENNReal :=
  PMF.lExpectation (N.calendarWasteLaw K U pi H) ENNReal.ofReal

private theorem expectedTrajectoryWasteFrom_nonneg {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (x : JobState Buffer K) (n : Nat) :
    0 <= N.expectedTrajectoryWasteFrom U x n := by
  unfold expectedTrajectoryWasteFrom
  apply Finset.sum_nonneg
  intro tokens _htokens
  exact mul_nonneg ENNReal.toReal_nonneg
    (N.trajectoryWaste_nonneg U x (List.ofFn tokens))

private theorem expectedTrajectoryWaste_nonneg {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (pi : PMF (JobState Buffer K)) (n : Nat) :
    0 <= N.expectedTrajectoryWaste U pi n := by
  unfold expectedTrajectoryWaste
  apply Finset.sum_nonneg
  intro x _hx
  exact mul_nonneg ENNReal.toReal_nonneg
    (N.expectedTrajectoryWasteFrom_nonneg U x n)

private theorem lExpectation_tokenVector_trajectoryWaste {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (x : JobState Buffer K) (n : Nat) :
    PMF.lExpectation (N.tokenVectorLaw n)
        (fun tokens =>
          ENNReal.ofReal
            (N.trajectoryWaste U x (List.ofFn tokens))) =
      ENNReal.ofReal (N.expectedTrajectoryWasteFrom U x n) := by
  rw [PMF.lExpectation, tsum_fintype]
  calc
    Finset.univ.sum (fun tokens =>
        N.tokenVectorLaw n tokens *
          ENNReal.ofReal
            (N.trajectoryWaste U x (List.ofFn tokens))) =
        Finset.univ.sum (fun tokens =>
          ENNReal.ofReal
            ((N.tokenVectorLaw n tokens).toReal *
              N.trajectoryWaste U x (List.ofFn tokens))) := by
      apply Finset.sum_congr rfl
      intro tokens _htokens
      rw [ENNReal.ofReal_mul ENNReal.toReal_nonneg,
        ENNReal.ofReal_toReal
          ((N.tokenVectorLaw n).apply_ne_top tokens)]
    _ = ENNReal.ofReal (N.expectedTrajectoryWasteFrom U x n) := by
      rw [expectedTrajectoryWasteFrom]
      symm
      apply ENNReal.ofReal_sum_of_nonneg
      intro tokens _htokens
      exact mul_nonneg ENNReal.toReal_nonneg
        (N.trajectoryWaste_nonneg U x (List.ofFn tokens))

private theorem lExpectation_initial_expectedTrajectoryWaste {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (pi : PMF (JobState Buffer K)) (n : Nat) :
    PMF.lExpectation pi
        (fun x => ENNReal.ofReal
          (N.expectedTrajectoryWasteFrom U x n)) =
      ENNReal.ofReal (N.expectedTrajectoryWaste U pi n) := by
  rw [PMF.lExpectation, tsum_fintype]
  calc
    Finset.univ.sum (fun x =>
        pi x * ENNReal.ofReal
          (N.expectedTrajectoryWasteFrom U x n)) =
        Finset.univ.sum (fun x =>
          ENNReal.ofReal
            ((pi x).toReal *
              N.expectedTrajectoryWasteFrom U x n)) := by
      apply Finset.sum_congr rfl
      intro x _hx
      rw [ENNReal.ofReal_mul ENNReal.toReal_nonneg,
        ENNReal.ofReal_toReal (pi.apply_ne_top x)]
    _ = ENNReal.ofReal (N.expectedTrajectoryWaste U pi n) := by
      rw [expectedTrajectoryWaste]
      symm
      apply ENNReal.ofReal_sum_of_nonneg
      intro x _hx
      exact mul_nonneg ENNReal.toReal_nonneg
        (N.expectedTrajectoryWasteFrom_nonneg U x n)

private theorem lExpectation_calendarWasteLawFrom
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (x : JobState Buffer (K : Nat)) (H : Real) :
    PMF.lExpectation (N.calendarWasteLawFrom K U x H)
        ENNReal.ofReal =
      ∑' n,
        StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
          ENNReal.ofReal (N.expectedTrajectoryWasteFrom U x n) := by
  rw [calendarWasteLawFrom, PMF.lExpectation_map]
  rw [StateDepMOR.Achievability.CalendarLaw.calendarTokenListLaw,
    PMF.lExpectation_bind]
  apply tsum_congr
  intro n
  congr 1
  rw [PMF.lExpectation_map]
  exact N.lExpectation_tokenVector_trajectoryWaste U x n

/-- Expansion of calendar expected waste by the Poisson event count. -/
theorem calendarExpectedWasteENN_eq_count_tsum
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat))) (H : Real) :
    N.calendarExpectedWasteENN K U pi H =
      ∑' n,
        StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
          ENNReal.ofReal (N.expectedTrajectoryWaste U pi n) := by
  rw [calendarExpectedWasteENN, calendarWasteLaw, PMF.lExpectation_bind]
  simp_rw [N.lExpectation_calendarWasteLawFrom K U _ H]
  calc
    (∑' x, pi x *
        ∑' n,
          StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
            ENNReal.ofReal (N.expectedTrajectoryWasteFrom U x n)) =
        ∑' x, ∑' n,
          pi x *
            (StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
              ENNReal.ofReal
                (N.expectedTrajectoryWasteFrom U x n)) := by
      apply tsum_congr
      intro x
      rw [ENNReal.tsum_mul_left]
    _ = ∑' n, ∑' x,
          pi x *
            (StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
              ENNReal.ofReal
                (N.expectedTrajectoryWasteFrom U x n)) :=
      ENNReal.tsum_comm
    _ = ∑' n,
          StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
            PMF.lExpectation pi
              (fun x => ENNReal.ofReal
                (N.expectedTrajectoryWasteFrom U x n)) := by
      apply tsum_congr
      intro n
      unfold PMF.lExpectation
      calc
        (∑' x,
            pi x *
              (StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
                K H n *
                ENNReal.ofReal
                  (N.expectedTrajectoryWasteFrom U x n))) =
            ∑' x,
              StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
                K H n *
                (pi x * ENNReal.ofReal
                  (N.expectedTrajectoryWasteFrom U x n)) := by
          apply tsum_congr
          intro x
          ac_rfl
        _ =
            StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
              ∑' x, pi x * ENNReal.ofReal
                (N.expectedTrajectoryWasteFrom U x n) :=
          ENNReal.tsum_mul_left
    _ = ∑' n,
          StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
            ENNReal.ofReal (N.expectedTrajectoryWaste U pi n) := by
      apply tsum_congr
      intro n
      rw [N.lExpectation_initial_expectedTrajectoryWaste U pi n]

/-- The total Poisson event count in a positive calendar interval has mean
`K * H`. -/
theorem calendarBlockCountLaw_hasSum_mul_nat
    (K : PNat) {H : Real} (hH : 0 <= H) :
    HasSum
      (fun n =>
        (StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
          K H n).toReal * (n : Real))
      (((K : Nat) : Real) * H) := by
  let r :=
    StateDepMOR.PaperStatements.Network.calendarBlockCountParameter K H
  have hmean :=
    ProbabilityTheory.hasSum_poissonMeasure_mul_nat r
  have hr :
      (r : Real) = ((K : Nat) : Real) * H := by
    change ((K : Nat) : Real) * max H 0 =
      ((K : Nat) : Real) * H
    rw [max_eq_left hH]
  rw [hr] at hmean
  exact HasSum.congr_fun hmean (fun n => by
    rw [StateDepMOR.PaperStatements.Network.calendarBlockCountLaw_apply_toReal
      K hH n])

/-- Under an invariant initial law, expected cumulative waste over a
calendar interval is exactly `K * H` times stationary event-epoch waste. -/
theorem calendarExpectedWasteENN_eq_ofReal_mul_stationary
    (K : PNat) {H : Real} (hH : 0 <= H)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat)))
    (hpi : N.IsInvariantPMF U pi) :
    N.calendarExpectedWasteENN K U pi H =
      ENNReal.ofReal
        ((((K : Nat) : Real) * H) *
          N.stationaryOneStepWaste U pi) := by
  rw [N.calendarExpectedWasteENN_eq_count_tsum]
  simp_rw [N.expectedTrajectoryWaste_eq_mul_stationary_of_invariant
    U pi hpi]
  let w := N.stationaryOneStepWaste U pi
  have hw : 0 <= w := N.stationaryOneStepWaste_nonneg U pi
  have hmean := calendarBlockCountLaw_hasSum_mul_nat K hH
  have hweighted :
      HasSum
        (fun n =>
          ((StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
            K H n).toReal * (n : Real)) * w)
        ((((K : Nat) : Real) * H) * w) :=
    hmean.mul_right w
  have htermNonneg (n : Nat) :
      0 <=
        ((StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
          K H n).toReal * (n : Real)) * w :=
    mul_nonneg
      (mul_nonneg ENNReal.toReal_nonneg (Nat.cast_nonneg n)) hw
  calc
    (∑' n,
        StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
          ENNReal.ofReal ((n : Real) * w)) =
        ∑' n, ENNReal.ofReal
          (((StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
            K H n).toReal * (n : Real)) * w) := by
      apply tsum_congr
      intro n
      calc
        StateDepMOR.PaperStatements.Network.calendarBlockCountLaw K H n *
            ENNReal.ofReal ((n : Real) * w) =
            ENNReal.ofReal
                ((StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
                  K H n).toReal) *
              ENNReal.ofReal ((n : Real) * w) := by
          rw [ENNReal.ofReal_toReal
            ((StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
              K H).apply_ne_top n)]
        _ = ENNReal.ofReal
              ((StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
                K H n).toReal * ((n : Real) * w)) :=
          (ENNReal.ofReal_mul ENNReal.toReal_nonneg).symm
        _ = ENNReal.ofReal
              (((StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
                K H n).toReal * (n : Real)) * w) := by
          congr 1
          ring
    _ = ENNReal.ofReal
          (∑' n,
            ((StateDepMOR.PaperStatements.Network.calendarBlockCountLaw
              K H n).toReal * (n : Real)) * w) := by
      exact (ENNReal.ofReal_tsum_of_nonneg
        htermNonneg hweighted.summable).symm
    _ = ENNReal.ofReal
          ((((K : Nat) : Real) * H) * w) := by
      rw [hweighted.tsum_eq]

/-- Real-valued expected cumulative calendar waste.  Finiteness follows
from the exact stationary identity whenever the initial law is invariant. -/
noncomputable def calendarExpectedWaste
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat))) (H : Real) : Real :=
  (N.calendarExpectedWasteENN K U pi H).toReal

theorem calendarExpectedWaste_eq_mul_stationary
    (K : PNat) {H : Real} (hH : 0 <= H)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat)))
    (hpi : N.IsInvariantPMF U pi) :
    N.calendarExpectedWaste K U pi H =
      (((K : Nat) : Real) * H) *
        N.stationaryOneStepWaste U pi := by
  rw [calendarExpectedWaste,
    N.calendarExpectedWasteENN_eq_ofReal_mul_stationary K hH U pi hpi]
  apply ENNReal.toReal_ofReal
  exact mul_nonneg
    (mul_nonneg (Nat.cast_nonneg _) hH)
    (N.stationaryOneStepWaste_nonneg U pi)

/-- The paper's finite-horizon normalization by total service-opportunity
rate `K` and elapsed calendar time `H`. -/
noncomputable def normalizedCalendarWaste
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat))) (H : Real) : Real :=
  N.calendarExpectedWaste K U pi H /
    (((K : Nat) : Real) * H)

theorem normalizedCalendarWaste_eq_stationary
    (K : PNat) {H : Real} (hH : 0 < H)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat)))
    (hpi : N.IsInvariantPMF U pi) :
    N.normalizedCalendarWaste K U pi H =
      N.stationaryOneStepWaste U pi := by
  rw [normalizedCalendarWaste,
    N.calendarExpectedWaste_eq_mul_stationary K hH.le U pi hpi]
  field_simp

/-- In particular, the normalized continuous-time expectation converges
to stationary event-epoch waste.  It is in fact equal at every positive
horizon. -/
theorem normalizedCalendarWaste_tendsto_stationary
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat))
    (pi : PMF (JobState Buffer (K : Nat)))
    (hpi : N.IsInvariantPMF U pi) :
    Tendsto
      (N.normalizedCalendarWaste K U pi)
      atTop
      (nhds (N.stationaryOneStepWaste U pi)) := by
  apply tendsto_const_nhds.congr'
  filter_upwards [eventually_gt_atTop (0 : Real)] with H hH
  exact (N.normalizedCalendarWaste_eq_stationary
    K hH U pi hpi).symm

/-- Values obtained as the paper's calendar-time limits over recurrent
communication classes. -/
def recurrentClassCalendarLimitSet
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat)) : Set Real :=
  {r | exists L : N.RecurrentClassLaw U,
    Tendsto
      (N.normalizedCalendarWaste K U L.law)
      atTop (nhds r)}

/-- The calendar-limit values are exactly the stationary reward values of
the recurrent classes. -/
theorem recurrentClassCalendarLimitSet_eq_recurrentClassLossSet
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat)) :
    N.recurrentClassCalendarLimitSet K U =
      N.recurrentClassLossSet U := by
  ext r
  constructor
  · rintro ⟨L, hlimit⟩
    have hstationary :=
      N.normalizedCalendarWaste_tendsto_stationary
        K U L.law L.isInvariant
    have hr :
        r = N.stationaryOneStepWaste U L.law :=
      tendsto_nhds_unique hlimit hstationary
    exact ⟨L, hr⟩
  · rintro ⟨L, rfl⟩
    exact ⟨L, N.normalizedCalendarWaste_tendsto_stationary
      K U L.law L.isInvariant⟩

/-- The performance quantity in the paper: minimum continuous-time
normalized expected waste over recurrent communication classes. -/
noncomputable def minimumCalendarRecurrentClassLoss
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat)) : Real :=
  sInf (N.recurrentClassCalendarLimitSet K U)

theorem minimumCalendarRecurrentClassLoss_eq_minimumRecurrentClassLoss
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat)) :
    N.minimumCalendarRecurrentClassLoss K U =
      N.minimumRecurrentClassLoss U := by
  rw [minimumCalendarRecurrentClassLoss,
    N.recurrentClassCalendarLimitSet_eq_recurrentClassLossSet,
    minimumRecurrentClassLoss]

/-- Full semantic bridge from the paper's continuous-time,
minimum-recurrent-class loss to the existing minimum-invariant-PMF loss. -/
theorem minimumCalendarRecurrentClassLoss_eq_minimumInvariantLoss
    (K : PNat)
    (U : N.DeterministicStationaryPolicy (K : Nat)) :
    N.minimumCalendarRecurrentClassLoss K U =
      N.minimumInvariantLoss U := by
  rw [N.minimumCalendarRecurrentClassLoss_eq_minimumRecurrentClassLoss,
    N.minimumRecurrentClassLoss_eq_minimumInvariantLoss]

/-- Paper-model loss for a policy sequence at every positive system size. -/
noncomputable def paperCalendarLossFamily
    (U : N.DeterministicPolicySequence) (K : PNat) : Real :=
  N.minimumCalendarRecurrentClassLoss K (U K)

theorem paperCalendarLossFamily_eq_minimumInvariantLossFamily
    (U : N.DeterministicPolicySequence) (K : PNat) :
    N.paperCalendarLossFamily U K =
      N.minimumInvariantLossFamily U K := by
  exact N.minimumCalendarRecurrentClassLoss_eq_minimumInvariantLoss K (U K)

theorem paperCalendarLossFamily_nonnegative
    (U : N.DeterministicPolicySequence) (K : PNat) :
    0 <= N.paperCalendarLossFamily U K := by
  rw [N.paperCalendarLossFamily_eq_minimumInvariantLossFamily]
  exact N.minimumInvariantLossFamily_nonnegative U K

theorem paperCalendarLossFamily_le_one
    (U : N.DeterministicPolicySequence) (K : PNat) :
    N.paperCalendarLossFamily U K <= 1 := by
  rw [N.paperCalendarLossFamily_eq_minimumInvariantLossFamily]
  exact N.minimumInvariantLossFamily_le_one U K

/-- Performance semantics built from the paper's original
continuous-time/minimum-recurrent-class definition. -/
noncomputable def paperCalendarPerformance :
    PerformanceSemantics N where
  loss := N.paperCalendarLossFamily
  loss_nonneg := N.paperCalendarLossFamily_nonnegative
  loss_le_one := N.paperCalendarLossFamily_le_one

@[simp]
theorem paperCalendarPerformance_loss
    (U : N.DeterministicPolicySequence) (K : PNat) :
    N.paperCalendarPerformance.loss U K =
      N.paperCalendarLossFamily U K :=
  rfl

theorem paperCalendarPerformance_eq_minimumInvariantPerformance :
    N.paperCalendarPerformance =
      N.minimumInvariantPerformance := by
  have hloss :
      N.paperCalendarPerformance.loss =
        N.minimumInvariantPerformance.loss := by
    funext U K
    exact N.paperCalendarLossFamily_eq_minimumInvariantLossFamily U K
  cases hp : N.paperCalendarPerformance with
  | mk paperLoss paperNonneg paperLeOne =>
      cases hm : N.minimumInvariantPerformance with
      | mk invariantLoss invariantNonneg invariantLeOne =>
          have hloss' : paperLoss = invariantLoss := by
            simpa [hp, hm] using hloss
          subst invariantLoss
          rfl

theorem paperCalendarThroughputLossExponent_eq
    (U : N.DeterministicPolicySequence) :
    N.paperCalendarPerformance.throughputLossExponent U =
      N.minimumInvariantPerformance.throughputLossExponent U := by
  rw [N.paperCalendarPerformance_eq_minimumInvariantPerformance]

end Network

namespace PaperStatements

/-- The paper's main theorem stated using its original continuous-time,
minimum-recurrent-class performance semantics. -/
noncomputable def PaperModelMainTightStatement
    (N : Network Buffer Server) [LinearOrder Buffer] : Prop :=
  N.IsConnected -> N.HasLimitedFlexibility -> N.HasCRP ->
    (forall (alpha : Simplex Buffer) (halpha : alpha.IsInterior),
      N.paperCalendarPerformance.throughputLossExponent
          (N.smwPolicy alpha halpha) =
        (N.explicitExponent alpha : EReal) /\
      0 < N.explicitExponent alpha) /\
    (forall U : N.DeterministicPolicySequence,
      N.paperCalendarPerformance.throughputLossExponent U <=
        smwExponentSup N) /\
    (forall epsilon : Real, 0 < epsilon ->
      exists (alpha : Simplex Buffer) (halpha : alpha.IsInterior),
        smwExponentSup N <
          N.paperCalendarPerformance.throughputLossExponent
              (N.smwPolicy alpha halpha) +
            (epsilon : EReal))

/-- The paper-model statement follows from the proved event-epoch theorem
through the calendar-time/minimum-recurrent-class semantic bridge. -/
theorem paperModelMainTightStatement
    (N : Network Buffer Server) [LinearOrder Buffer] :
    PaperModelMainTightStatement N := by
  unfold PaperModelMainTightStatement
  rw [Network.paperCalendarPerformance_eq_minimumInvariantPerformance]
  exact mainTightStatement N

end PaperStatements

end StateDepMOR
