import StateDepMOR.FiniteQueueLongRun
import StateDepMOR.MinInvariantPerformance

/-!
# Recurrent-class performance for the finite queue

This module connects the event-epoch definition based on all invariant PMFs
to the paper's minimum over recurrent communication classes.  Communication
is generated by transitions of strictly positive probability.
-/

open scoped BigOperators ENNReal

noncomputable section

namespace StateDepMOR

universe u v

variable {Buffer : Type u} {Server : Type v}
variable [Fintype Buffer] [Fintype Server]
variable [DecidableEq Buffer] [DecidableEq Server]

namespace Network

variable (N : Network Buffer Server)

/-- A positive-probability transition of the event-epoch queue chain. -/
def HasPositiveTransition {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (x y : JobState Buffer K) : Prop :=
  y ∈ (N.transitionPMF U x).support

/-- Reachability by a finite (possibly empty) sequence of positive
event-epoch transitions. -/
def EventReachable {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (x y : JobState Buffer K) : Prop :=
  Relation.ReflTransGen (N.HasPositiveTransition U) x y

/-- Two queue states communicate when each is reachable from the other. -/
def EventCommunicates {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (x y : JobState Buffer K) : Prop :=
  N.EventReachable U x y /\ N.EventReachable U y x

/-- A closed communicating class of the finite event-epoch chain.  On a
finite chain these are exactly the recurrent communication classes. -/
structure RecurrentClass {K : Nat}
    (U : N.DeterministicStationaryPolicy K) where
  carrier : Finset (JobState Buffer K)
  nonempty : carrier.Nonempty
  communicates :
    ∀ x ∈ carrier, ∀ y ∈ carrier,
      N.EventCommunicates U x y
  closed :
    ∀ x ∈ carrier, ∀ y,
      N.HasPositiveTransition U x y -> y ∈ carrier

/-- A recurrent class together with its stationary law.  The support
equality states that this is the invariant distribution on that class. -/
structure RecurrentClassLaw {K : Nat}
    (U : N.DeterministicStationaryPolicy K) where
  recurrentClass : N.RecurrentClass U
  law : PMF (JobState Buffer K)
  isInvariant : N.IsInvariantPMF U law
  support_eq :
    law.support = (recurrentClass.carrier : Set (JobState Buffer K))

/-- The finite support of a PMF. -/
private noncomputable def pmfSupportFinset
    (_N : Network Buffer Server) {K : Nat}
    (pi : PMF (JobState Buffer K)) : Finset (JobState Buffer K) :=
  by
    classical
    exact Finset.univ.filter fun x => x ∈ pi.support

/-- The finite set reachable from one queue state. -/
private noncomputable def reachableFinset {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (x : JobState Buffer K) : Finset (JobState Buffer K) :=
  by
    classical
    exact Finset.univ.filter fun y => N.EventReachable U x y

private theorem mem_pmfSupportFinset_iff {K : Nat}
    (pi : PMF (JobState Buffer K)) (x : JobState Buffer K) :
    x ∈ N.pmfSupportFinset pi ↔ x ∈ pi.support := by
  simp [pmfSupportFinset]

private theorem mem_reachableFinset_iff {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (x y : JobState Buffer K) :
    y ∈ N.reachableFinset U x ↔ N.EventReachable U x y := by
  simp [reachableFinset]

/-- The support of an invariant PMF is closed under every positive
transition. -/
theorem invariant_support_closed {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (pi : PMF (JobState Buffer K))
    (hpi : N.IsInvariantPMF U pi)
    {x y : JobState Buffer K}
    (hx : x ∈ pi.support)
    (hxy : N.HasPositiveTransition U x y) :
    y ∈ pi.support := by
  have hy :
      y ∈ (pi.bind (N.transitionPMF U)).support :=
    (PMF.mem_support_bind_iff pi (N.transitionPMF U) y).2
      ⟨x, hx, hxy⟩
  rwa [hpi] at hy

/-- Consequently, invariant support is closed under finite reachability. -/
theorem invariant_support_closed_reachable {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (pi : PMF (JobState Buffer K))
    (hpi : N.IsInvariantPMF U pi)
    {x y : JobState Buffer K}
    (hx : x ∈ pi.support)
    (hxy : N.EventReachable U x y) :
    y ∈ pi.support := by
  induction hxy with
  | refl =>
      exact hx
  | tail hab hbc ih =>
      exact N.invariant_support_closed U pi hpi ih hbc

/-- Every invariant support contains a closed communicating class. -/
theorem exists_recurrentClass_subset_support {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (pi : PMF (JobState Buffer K))
    (hpi : N.IsInvariantPMF U pi) :
    exists C : N.RecurrentClass U,
      (C.carrier : Set (JobState Buffer K)) ⊆ pi.support := by
  classical
  have hsupport :
      (N.pmfSupportFinset pi).Nonempty := by
    obtain ⟨x, hx⟩ := pi.support_nonempty
    exact ⟨x, (N.mem_pmfSupportFinset_iff pi x).2 hx⟩
  obtain ⟨x, hxSupport, hxMinimal⟩ :=
    Finset.exists_min_image
      (N.pmfSupportFinset pi)
      (fun z => (N.reachableFinset U z).card)
      hsupport
  let carrier := N.reachableFinset U x
  have hxCarrier : x ∈ carrier := by
    exact (N.mem_reachableFinset_iff U x x).2
      Relation.ReflTransGen.refl
  have hcarrierSupport :
      (carrier : Set (JobState Buffer K)) ⊆ pi.support := by
    intro y hy
    have hxy : N.EventReachable U x y :=
      (N.mem_reachableFinset_iff U x y).1 hy
    exact N.invariant_support_closed_reachable U pi hpi
      ((N.mem_pmfSupportFinset_iff pi x).1 hxSupport) hxy
  have hback :
      ∀ a ∈ carrier, N.EventReachable U a x := by
    intro a ha
    have hxa : N.EventReachable U x a :=
      (N.mem_reachableFinset_iff U x a).1 ha
    have hsubset :
        N.reachableFinset U a ⊆ carrier := by
      intro z hz
      have haz : N.EventReachable U a z :=
        (N.mem_reachableFinset_iff U a z).1 hz
      exact (N.mem_reachableFinset_iff U x z).2 (hxa.trans haz)
    have haSupportFinset : a ∈ N.pmfSupportFinset pi :=
      (N.mem_pmfSupportFinset_iff pi a).2 (hcarrierSupport ha)
    have hcard :
        carrier.card <= (N.reachableFinset U a).card :=
      hxMinimal a haSupportFinset
    have heq : N.reachableFinset U a = carrier :=
      Finset.eq_of_subset_of_card_le hsubset hcard
    exact (N.mem_reachableFinset_iff U a x).1
      (by simpa [heq] using hxCarrier)
  let C : N.RecurrentClass U :=
    { carrier := carrier
      nonempty := ⟨x, hxCarrier⟩
      communicates := by
        intro a ha b hb
        have hax := hback a ha
        have hxb : N.EventReachable U x b :=
          (N.mem_reachableFinset_iff U x b).1 hb
        have hbx := hback b hb
        have hxa : N.EventReachable U x a :=
          (N.mem_reachableFinset_iff U x a).1 ha
        exact ⟨hax.trans hxb, hbx.trans hxa⟩
      closed := by
        intro a ha b hab
        have hxa : N.EventReachable U x a :=
          (N.mem_reachableFinset_iff U x a).1 ha
        exact (N.mem_reachableFinset_iff U x b).2
          (hxa.tail hab) }
  exact ⟨C, hcarrierSupport⟩

private theorem nStepLaw_pure_support_subset_recurrentClass {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (C : N.RecurrentClass U)
    (x : JobState Buffer K) (hx : x ∈ C.carrier) :
    ∀ n,
      (N.nStepLaw U (PMF.pure x) n).support ⊆
        (C.carrier : Set (JobState Buffer K)) := by
  intro n
  induction n with
  | zero =>
      intro y hy
      have hyx : y = x :=
        (PMF.mem_support_pure_iff x y).1 (by simpa using hy)
      simpa [hyx] using hx
  | succ n ih =>
      intro y hy
      rw [N.nStepLaw_succ] at hy
      obtain ⟨z, hz, hzy⟩ :=
        (PMF.mem_support_bind_iff
          (N.nStepLaw U (PMF.pure x) n)
          (N.transitionPMF U) y).1 hy
      exact C.closed z (ih hz) y hzy

private theorem occupationPMF_pure_support_subset_recurrentClass {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (C : N.RecurrentClass U)
    (x : JobState Buffer K) (hx : x ∈ C.carrier)
    (n : Nat) :
    (N.occupationPMF U (PMF.pure x) n).support ⊆
      (C.carrier : Set (JobState Buffer K)) := by
  intro y hy
  unfold occupationPMF at hy
  obtain ⟨k, _hk, hky⟩ :=
    (PMF.mem_support_bind_iff
      (PMF.uniformOfFintype (Fin (n + 1)))
      (fun k => N.nStepLaw U (PMF.pure x) k) y).1 hy
  exact N.nStepLaw_pure_support_subset_recurrentClass
    U C x hx k hky

/-- Every recurrent communication class carries an invariant PMF whose
support is exactly that class. -/
theorem exists_recurrentClassLaw {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (C : N.RecurrentClass U) :
    exists L : N.RecurrentClassLaw U, L.recurrentClass = C := by
  classical
  obtain ⟨x, hx⟩ := C.nonempty
  obtain ⟨rho, hrhoInvariant, hcoordinate, _hwaste⟩ :=
    N.exists_initialCesaroLimitPMF U (PMF.pure x)
  have hrhoSubset :
      rho.support ⊆
        (C.carrier : Set (JobState Buffer K)) := by
    intro y hy
    by_contra hyC
    have hzero :
        ∀ n, (N.occupationPMF U (PMF.pure x) n y).toReal = 0 := by
      intro n
      rw [ENNReal.toReal_eq_zero_iff]
      left
      apply (N.occupationPMF U (PMF.pure x) n).apply_eq_zero_iff y |>.2
      intro hySupport
      exact hyC
        (N.occupationPMF_pure_support_subset_recurrentClass
          U C x hx n hySupport)
    have htendZero :
        Filter.Tendsto
          (fun n => (N.occupationPMF U (PMF.pure x) n y).toReal)
          Filter.atTop (nhds 0) := by
      simpa only [hzero] using
        (tendsto_const_nhds :
          Filter.Tendsto (fun _ : Nat => (0 : Real))
            Filter.atTop (nhds 0))
    have hrhoZero : (rho y).toReal = 0 :=
      tendsto_nhds_unique (hcoordinate y) htendZero
    have hrhoApplyZero : rho y = 0 := by
      rw [ENNReal.toReal_eq_zero_iff] at hrhoZero
      exact hrhoZero.resolve_right (rho.apply_ne_top y)
    exact hy hrhoApplyZero
  have hclassSubset :
      (C.carrier : Set (JobState Buffer K)) ⊆ rho.support := by
    obtain ⟨z, hzSupport⟩ := rho.support_nonempty
    have hzClass : z ∈ C.carrier := hrhoSubset hzSupport
    intro y hyClass
    have hreachable : N.EventReachable U z y :=
      (C.communicates z hzClass y hyClass).1
    exact N.invariant_support_closed_reachable U rho
      hrhoInvariant hzSupport hreachable
  let L : N.RecurrentClassLaw U :=
    { recurrentClass := C
      law := rho
      isInvariant := hrhoInvariant
      support_eq := Set.Subset.antisymm hrhoSubset hclassSubset }
  exact ⟨L, rfl⟩

private theorem pmf_toReal_le_one
    (_N : Network Buffer Server) {K : Nat}
    (pi : PMF (JobState Buffer K)) (x : JobState Buffer K) :
    (pi x).toReal <= 1 := by
  have h := (ENNReal.toReal_le_toReal
    (pi.apply_ne_top x) (by simp : Ne (1 : ENNReal) ⊤)).2
      (pi.coe_le_one x)
  simpa using h

private theorem bind_toReal {K : Nat}
    (pi : PMF (JobState Buffer K))
    (U : N.DeterministicStationaryPolicy K)
    (y : JobState Buffer K) :
    ((pi.bind (N.transitionPMF U)) y).toReal =
      Finset.univ.sum fun x =>
        (pi x).toReal * (N.transitionPMF U x y).toReal := by
  rw [PMF.bind_apply, tsum_fintype]
  rw [ENNReal.toReal_sum (fun x _ =>
    ENNReal.mul_ne_top (pi.apply_ne_top x)
      ((N.transitionPMF U x).apply_ne_top y))]
  simp only [ENNReal.toReal_mul]

/-- If the support of one invariant law is contained in that of another,
the larger law has a nontrivial invariant residual after subtracting a
small multiple of the smaller law. -/
private theorem exists_invariant_residual {K : Nat}
    (U : N.DeterministicStationaryPolicy K)
    (pi rho : PMF (JobState Buffer K))
    (hpi : N.IsInvariantPMF U pi)
    (hrho : N.IsInvariantPMF U rho)
    (hsupport : rho.support ⊆ pi.support) :
    exists (a : Real) (sigma : PMF (JobState Buffer K)),
      0 < a /\ a < 1 /\
      N.IsInvariantPMF U sigma /\
      (forall x,
        (pi x).toReal =
          a * (rho x).toReal + (1 - a) * (sigma x).toReal) := by
  classical
  let support := N.pmfSupportFinset rho
  have hsupportNonempty : support.Nonempty := by
    obtain ⟨x, hx⟩ := rho.support_nonempty
    exact ⟨x, (N.mem_pmfSupportFinset_iff rho x).2 hx⟩
  let b : Real :=
    support.inf' hsupportNonempty fun x => (pi x).toReal
  have hbpos : 0 < b := by
    rw [show b =
      support.inf' hsupportNonempty (fun x => (pi x).toReal) by rfl]
    rw [Finset.lt_inf'_iff]
    intro x hx
    exact ENNReal.toReal_pos
      ((pi.mem_support_iff x).1
        (hsupport ((N.mem_pmfSupportFinset_iff rho x).1 hx)))
      (pi.apply_ne_top x)
  have hble : ∀ x ∈ support, b <= (pi x).toReal := by
    intro x hx
    exact Finset.inf'_le (fun y => (pi y).toReal) hx
  have hbone : b <= 1 := by
    obtain ⟨x, hx⟩ := hsupportNonempty
    exact (hble x hx).trans (N.pmf_toReal_le_one pi x)
  let a := b / 2
  have hapos : 0 < a := div_pos hbpos (by norm_num)
  have halt : a < 1 := by
    dsimp only [a]
    linarith
  have hane : 1 - a ≠ 0 := ne_of_gt (sub_pos.2 halt)
  have hdom (x : JobState Buffer K) :
      a * (rho x).toReal <= (pi x).toReal := by
    by_cases hx : x ∈ rho.support
    · have hxFinset : x ∈ support :=
        (N.mem_pmfSupportFinset_iff rho x).2 hx
      have hrhoLe : (rho x).toReal <= 1 :=
        N.pmf_toReal_le_one rho x
      have haNonneg : 0 <= a := hapos.le
      calc
        a * (rho x).toReal <= a * 1 :=
          mul_le_mul_of_nonneg_left hrhoLe haNonneg
        _ = a := mul_one a
        _ <= b := by
          dsimp only [a]
          linarith
        _ <= (pi x).toReal := hble x hxFinset
    · have hrhoZero : rho x = 0 :=
        (rho.apply_eq_zero_iff x).2 hx
      simp [hrhoZero, ENNReal.toReal_nonneg]
  let q : JobState Buffer K -> Real := fun x =>
    ((pi x).toReal - a * (rho x).toReal) / (1 - a)
  have hqnonneg (x : JobState Buffer K) : 0 <= q x := by
    exact div_nonneg (sub_nonneg.2 (hdom x)) (sub_nonneg.2 halt.le)
  have hqsum : Finset.univ.sum q = 1 := by
    calc
      Finset.univ.sum q =
          (Finset.univ.sum (fun x =>
            (pi x).toReal - a * (rho x).toReal)) / (1 - a) := by
        rw [Finset.sum_div]
      _ =
          (Finset.univ.sum (fun x => (pi x).toReal) -
            a * Finset.univ.sum (fun x => (rho x).toReal)) /
              (1 - a) := by
        rw [Finset.sum_sub_distrib, Finset.mul_sum]
      _ = 1 := by
        rw [PMF.sum_toReal, PMF.sum_toReal]
        field_simp [hane]
  let sigma : PMF (JobState Buffer K) :=
    PMF.ofFintype (fun x => ENNReal.ofReal (q x)) (by
      rw [(ENNReal.ofReal_sum_of_nonneg
        (s := Finset.univ) (fun x _ => hqnonneg x)).symm]
      rw [hqsum]
      simp)
  have hsigmaToReal (x : JobState Buffer K) :
      (sigma x).toReal = q x := by
    change (ENNReal.ofReal (q x)).toReal = q x
    exact ENNReal.toReal_ofReal (hqnonneg x)
  have hpiMatrix (y : JobState Buffer K) :
      Finset.univ.sum (fun x =>
        (pi x).toReal * (N.transitionPMF U x y).toReal) =
          (pi y).toReal := by
    rw [← N.bind_toReal pi U y, hpi]
  have hrhoMatrix (y : JobState Buffer K) :
      Finset.univ.sum (fun x =>
        (rho x).toReal * (N.transitionPMF U x y).toReal) =
          (rho y).toReal := by
    rw [← N.bind_toReal rho U y, hrho]
  have hsigmaInvariant : N.IsInvariantPMF U sigma := by
    apply PMF.ext
    intro y
    apply (ENNReal.toReal_eq_toReal_iff'
      ((sigma.bind (N.transitionPMF U)).apply_ne_top y)
      (sigma.apply_ne_top y)).mp
    rw [N.bind_toReal]
    simp_rw [hsigmaToReal]
    simp only [q]
    calc
      Finset.univ.sum (fun x =>
          (((pi x).toReal - a * (rho x).toReal) / (1 - a)) *
            (N.transitionPMF U x y).toReal) =
          Finset.univ.sum (fun x =>
            ((pi x).toReal * (N.transitionPMF U x y).toReal -
              a * ((rho x).toReal *
                (N.transitionPMF U x y).toReal)) / (1 - a)) := by
        apply Finset.sum_congr rfl
        intro x _hx
        ring
      _ =
          (Finset.univ.sum (fun x =>
            (pi x).toReal * (N.transitionPMF U x y).toReal -
              a * ((rho x).toReal *
                (N.transitionPMF U x y).toReal))) / (1 - a) := by
        rw [Finset.sum_div]
      _ =
          ((pi y).toReal - a * (rho y).toReal) / (1 - a) := by
        rw [Finset.sum_sub_distrib, ← Finset.mul_sum,
          hpiMatrix, hrhoMatrix]
  refine ⟨a, sigma, hapos, halt, hsigmaInvariant, ?_⟩
  intro x
  rw [hsigmaToReal]
  dsimp only [q]
  field_simp [hane]
  ring

/-- Some recurrent-class stationary law attains the minimum over all
invariant PMFs. -/
theorem exists_minimizingRecurrentClassLaw {K : Nat}
    (U : N.DeterministicStationaryPolicy K) :
    exists L : N.RecurrentClassLaw U,
      N.stationaryOneStepWaste U L.law =
        N.minimumInvariantLoss U := by
  obtain ⟨pi, hpiInvariant, hpiMinimum⟩ :=
    N.exists_minimumInvariantLossPMF U
  obtain ⟨C, hCsubset⟩ :=
    N.exists_recurrentClass_subset_support U pi hpiInvariant
  obtain ⟨L, hLC⟩ := N.exists_recurrentClassLaw U C
  have hLsupport : L.law.support ⊆ pi.support := by
    rw [L.support_eq, hLC]
    exact hCsubset
  obtain ⟨a, sigma, hapos, halt, hsigmaInvariant, hmixture⟩ :=
    N.exists_invariant_residual U pi L.law
      hpiInvariant L.isInvariant hLsupport
  have hwasteMixture :
      N.stationaryOneStepWaste U pi =
        a * N.stationaryOneStepWaste U L.law +
          (1 - a) * N.stationaryOneStepWaste U sigma := by
    unfold stationaryOneStepWaste
    calc
      Finset.univ.sum (fun x =>
          (pi x).toReal * N.oneStepWaste U x) =
          Finset.univ.sum (fun x =>
            (a * (L.law x).toReal +
                (1 - a) * (sigma x).toReal) *
              N.oneStepWaste U x) := by
        apply Finset.sum_congr rfl
        intro x _hx
        rw [hmixture x]
      _ =
          a * Finset.univ.sum (fun x =>
              (L.law x).toReal * N.oneStepWaste U x) +
            (1 - a) * Finset.univ.sum (fun x =>
              (sigma x).toReal * N.oneStepWaste U x) := by
        simp_rw [add_mul, mul_assoc]
        rw [Finset.sum_add_distrib, Finset.mul_sum, Finset.mul_sum]
  have hpiWaste :
      N.stationaryOneStepWaste U pi =
        N.minimumInvariantLoss U :=
    hpiMinimum.symm
  have hminimumL :
      N.minimumInvariantLoss U <=
        N.stationaryOneStepWaste U L.law :=
    N.minimumInvariantLoss_le_stationaryOneStepWaste
      U L.law L.isInvariant
  have hminimumSigma :
      N.minimumInvariantLoss U <=
        N.stationaryOneStepWaste U sigma :=
    N.minimumInvariantLoss_le_stationaryOneStepWaste
      U sigma hsigmaInvariant
  refine ⟨L, ?_⟩
  nlinarith

/-- Stationary waste values of the recurrent communication classes. -/
def recurrentClassLossSet {K : Nat}
    (U : N.DeterministicStationaryPolicy K) : Set Real :=
  {r | exists L : N.RecurrentClassLaw U,
    r = N.stationaryOneStepWaste U L.law}

theorem recurrentClassLossSet_nonempty {K : Nat}
    (U : N.DeterministicStationaryPolicy K) :
    (N.recurrentClassLossSet U).Nonempty := by
  obtain ⟨L, hL⟩ := N.exists_minimizingRecurrentClassLaw U
  exact ⟨N.stationaryOneStepWaste U L.law, L, rfl⟩

theorem recurrentClassLossSet_bddBelow {K : Nat}
    (U : N.DeterministicStationaryPolicy K) :
    BddBelow (N.recurrentClassLossSet U) := by
  refine ⟨0, ?_⟩
  intro r hr
  obtain ⟨L, rfl⟩ := hr
  exact N.stationaryOneStepWaste_nonneg U L.law

/-- The paper's minimum over recurrent communication classes, expressed
using the invariant law supported on each class. -/
noncomputable def minimumRecurrentClassLoss {K : Nat}
    (U : N.DeterministicStationaryPolicy K) : Real :=
  sInf (N.recurrentClassLossSet U)

/-- The minimum over recurrent classes is exactly the minimum over all
invariant PMFs used by the existing proof. -/
theorem minimumRecurrentClassLoss_eq_minimumInvariantLoss {K : Nat}
    (U : N.DeterministicStationaryPolicy K) :
    N.minimumRecurrentClassLoss U =
      N.minimumInvariantLoss U := by
  apply le_antisymm
  · obtain ⟨L, hL⟩ := N.exists_minimizingRecurrentClassLaw U
    unfold minimumRecurrentClassLoss
    apply le_trans
      (csInf_le (N.recurrentClassLossSet_bddBelow U)
        (show N.minimumInvariantLoss U ∈
          N.recurrentClassLossSet U from ⟨L, hL.symm⟩))
      le_rfl
  · unfold minimumRecurrentClassLoss
    apply le_csInf (N.recurrentClassLossSet_nonempty U)
    intro r hr
    obtain ⟨L, rfl⟩ := hr
    exact N.minimumInvariantLoss_le_stationaryOneStepWaste
      U L.law L.isInvariant

theorem minimumRecurrentClassLoss_nonnegative {K : Nat}
    (U : N.DeterministicStationaryPolicy K) :
    0 <= N.minimumRecurrentClassLoss U := by
  rw [N.minimumRecurrentClassLoss_eq_minimumInvariantLoss]
  exact N.minimumInvariantLoss_nonnegative U

theorem minimumRecurrentClassLoss_le_one {K : Nat}
    (U : N.DeterministicStationaryPolicy K) :
    N.minimumRecurrentClassLoss U <= 1 := by
  rw [N.minimumRecurrentClassLoss_eq_minimumInvariantLoss]
  exact N.minimumInvariantLoss_le_one U

end Network

end StateDepMOR
